services:
  # Ollama app & Stramlit GUI
  app:
    build: .
    container_name: ollama_streamlit_app
    ports:
      - "11434:11434" # Ollama API port
      - "8501:8501"   # Streamlit GUI port
    volumes:
      - ./ollama_app:/app # Persist Ollama models
      - log_data:/log
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Deepstream app 
  deepstream:
    build: ./deepstream_app
    container_name: deepstream_app
    stdin_open: true 
    tty: true
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=/opt/nvidia/deepstream/deepstream-7.1/sources/deepstream_python_apps/apps/
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./deepstream_app:/app
      - log_data:/log
    devices:
      - "/dev/video0:/dev/video0"
    working_dir: /app
    command: python3 deepstream-camera.py /dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
   log_data:
