version: '3.8'

services:
  app:
    # Build a custom image from the Dockerfile in the current directory
    build: .
    container_name: ollama_streamlit_app
    ports:
      - "11434:11434" # Expose Ollama's API port
      - "8501:8501"   # Expose Streamlit's GUI port
    volumes:
      - ollama_data:/root/.ollama # Persist Ollama models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:
