services:
  # Ollama app & Stramlit GUI
  app:
    build: .
    container_name: ollama_streamlit_app
    ports:
      - "11434:11434" # Ollama API port
      - "8501:8501"   # Streamlit GUI port
    volumes:
      - ollama_data:/root/.ollama # Persist Ollama models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Deepstream app 
  deepstream:
    build: ./deepstream_app
    container_name: deepstream_app
    stdin_open: true 
    tty: true
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./deepstream_app:/app
    devices:
      - "/dev/video0:/dev/video0"
    working_dir: /app
    command: python3 deepstream-camera.py /dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:
